version: '3'

services:
  bchurrasco-app:
    container_name: bchurrasco
    build:
      context: .
      dockerfile: ./.docker/development/php/Dockerfile
    restart: always
    working_dir: /var/www/application
    ports:
      - "9000:80"
    volumes:
      - ./:/var/www/application
      - ./.docker/development/php/www.conf:/var/data/php-fpm/www.tmpl.conf
      - ./.docker/development/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./.docker/development/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ~/.ssh:/root/.ssh
      - ~/.gitconfig:/root/.gitconfig

  bchurrasco-db:
    container_name: mysql8
    image: mysql:8.0
    command: mysqld --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: bchurrasco
      MYSQL_PASSWORD: passpass
      # MYSQL_USER: sandbox_user
      # MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - '3306:3306'
    volumes:
      - './.docker/development/db/data:/var/lib/mysql'
      - './.docker/development/db/my.cnf:/etc/mysql/conf.d/my.cnf'